### ISSUE TITLE
Types missing

### ISSUE THREAD

**Issue by WolleKette** [fancidev/asyncslot#2]
Hi,
I'm confused. When I try to run the example (on macos), it already fails when importing asyncSlot and AsyncSlotRunner. 
And in the sources, I can't find such types. What's happen?

**Comment by fancidev** [comment]
Hi, did you check out the source repo or pip install?

If you checked out source repo, please ensure the src folder is in PYTHONPATH environment variable.

If you did pip install, the current pip package is outdated so it may not work. I’ll upload an updated package after Windows support is ready (a few days).

**Comment by WolleKette** [comment]
Hi, 
for my tests, I used the pip package. 
But I saw that you've already published the new version 0.1.1. And with that, I was able to run the examples. Many thanks for this! 👍 

I want to use asyncslot to call the asynchronous routines of the Bluetooth module bleak. And at least the scanning of devices works now with asyncslot.

**Comment by WolleKette** [comment]
.

**Comment by fancidev** [comment]
@WolleKette, fyi, I’ve renamed the project from “asyncslot” to “qtinter” with more complete functionality. Below are the  API changes:

asyncslot.asyncSlot becomes qtinter.asyncslot

asyncslot.AsyncSlotRunner becomes qtinter.using_asyncio_from_qt

Please check it out if you like :-)
